#!/usr/bin/env bun
// Rewrites the key map in README.md (between the keys:begin and keys:end markers) from src/keys.ts.
// test/docs-text.test.ts fails when the README is out of date, so run this after changing an action.
import { keysMarkdown } from "../src/keys.ts";

export const BEGIN = "<!-- keys:begin (generated by scripts/build-readme-keys.ts from src/keys.ts) -->";
export const END = "<!-- keys:end -->";

if (import.meta.main) {
  const path = new URL("../README.md", import.meta.url).pathname;
  const text = await Bun.file(path).text();
  const a = text.indexOf("<!-- keys:begin"), b = text.indexOf(END);
  if (a < 0 || b < a) { console.error("README.md has no keys:begin / keys:end markers"); process.exit(1); }
  await Bun.write(path, `${text.slice(0, a)}${BEGIN}\n\n${keysMarkdown()}\n\n${text.slice(b)}`);
}
