// `a s`: the model drafts a submission for the reader to review: which findings to include, a verdict, and a short
// top-level comment. One call to the `ask` role, no tools. What comes back is only a suggestion: it pre-fills the submit
// flow (submit-flow.ts startFlow), where the reader changes anything, and nothing is sent until Enter on Send.
//
// Everything the model reads from the change (titles, claims, evidence, the reader's own notes) is fenced as data, and the
// reply is read defensively: ids that are not listed, a verdict the platform lacks and tooling talk in the comment are dropped.

import type { Config, Lookups, Resolved } from "./config.ts";
import { loadConfig, realLookups, resolveModel, roleModel } from "./config.ts";
import type { Review, Run } from "./build.ts";
import type { Finding } from "./guide.ts";
import { DATA_RULE, fence, titleOf } from "./guide.ts";
import { complete } from "./llm.ts";
import { clean } from "./sanitize.ts";
import type { Draft } from "./submit-flow.ts";
import { actionOf, actionText, type Defaults, DEFAULTS } from "./triage.ts";
import type { Verdict } from "./document.ts";

export const DRAFT_SYSTEM = `You help a human reviewer decide what to send on a code review. You are given the change and the findings raised on it (each with the reviewer's current action on it, if any). Propose a submission for the reviewer to edit: which findings are worth posting, the verdict, and a short top-level comment.
Reply with one JSON object and nothing else:
{"include": ["<finding id>", ...], "verdict": "approve" | "request_changes" | "comment", "comment": "<text>"}
- "include": ids from the list only, the findings a careful reviewer would actually raise with the author. Leave out ones that are weak, already handled or nitpicks. Use "request_changes" only when an included finding is serious enough to block.
- "comment": two to five plain sentences in the reviewer's own first-person voice, about the change itself. Never mention a tool, a model, an assistant, automation or where the findings came from.
${DATA_RULE}`;

/** The prompt: the change and every finding, all as fenced data. `verdicts` are the ones the platform takes. */
export function draftPrompt(doc: Review["doc"], findings: Finding[], verdicts: Verdict[], defaults: Defaults = DEFAULTS): string {
  const list = findings.map((f) => fence("finding", [
    `id: ${f.id}`, `${f.severity} · ${f.kind}`, `where: ${f.file ? "whole file" : `${f.side === "new" ? "new" : "old"} line ${f.line}`}`,
    `current action: ${actionText(actionOf(doc.human, f, defaults))}`, `title: ${titleOf(f)}`, `claim: ${f.claim}`, `evidence: ${f.evidence}`, ...(f.refute ? [`second look: ${f.refute}`] : []),
  ].join("\n")));
  return `# The change\n${fence("title", doc.target.title)}\n${fence("summary", doc.plan.summary)}\n\n## The findings\n${list.length ? list.join("\n\n") : "(none)"}\n\n## Verdicts available\n${verdicts.join(", ")}`;
}

/** Sentences that talk about the tooling are dropped: a posted comment is the reviewer's own words. */
const TOOLING = /\b(prview|claude|anthropic|openai|gpt|llm|ai|a\.i\.|language models?|models?|assistants?|bots?|automated|auto-generated|generated by|ai-generated)\b/i;
export function plainVoice(text: string): string {
  const sentences = clean(text).replace(/[ \t]+/g, " ").trim().split(/(?<=[.!?])\s+/);
  return sentences.filter((s) => !TOOLING.test(s)).join(" ").trim().slice(0, 2000);
}

/** The draft in a reply: the first JSON object in it, each part kept only when it is usable. Never throws. */
export function readDraft(text: string, listed: string[], verdicts: Verdict[]): Draft {
  const a = text.indexOf("{"), b = text.lastIndexOf("}");
  let j: any;
  try { j = JSON.parse(text.slice(a, b + 1)); } catch { return {}; }
  if (typeof j !== "object" || j === null || Array.isArray(j)) return {};
  const out: Draft = {};
  if (Array.isArray(j.include)) out.include = [...new Set(j.include.map(String))].filter((id) => listed.includes(id as string)) as string[];
  const v = typeof j.verdict === "string" ? j.verdict.trim().toLowerCase().replace(/[\s-]+/g, "_") : "";
  if ((verdicts as string[]).includes(v)) out.verdict = v as Verdict;
  if (typeof j.comment === "string") { const c = plainVoice(j.comment); if (c) out.comment = c; }
  return out;
}

export type DraftDeps = { cfg?: Config; lookups?: Lookups; call?: typeof complete };

/**
 * Ask for a draft over `findings` (every one the reader may see, whatever the filter). The model is the `ask` role as
 * the config has it now. The run goes into `ai.runs`; the caller saves the review. Throws when the model cannot be
 * reached or its reply holds no usable draft.
 */
export async function draftSubmission(r: Review, findings: Finding[], verdicts: Verdict[], defaults: Defaults = DEFAULTS, deps: DraftDeps = {}): Promise<Draft> {
  const cfg = deps.cfg ?? loadConfig();
  const m: Resolved = resolveModel(cfg, roleModel(cfg, "ask"), deps.lookups ?? realLookups());
  const t0 = Date.now();
  let cost: number | undefined, model: string | undefined;
  const text = await (deps.call ?? complete)(m, DRAFT_SYSTEM, draftPrompt(r.doc, findings, verdicts, defaults), (u) => { cost = u.cost; model = u.model; });
  const draft = readDraft(text, findings.map((f) => f.id), verdicts);
  const run: Run = { role: "ask", name: m.def.name, model: model ?? m.def.model, ms: Date.now() - t0, ...(cost !== undefined ? { cost } : {}) };
  const at = new Date().toISOString();
  r.ai = r.ai ? { ...r.ai, runs: [...(r.ai.runs ?? []), run] } : { models: {}, at, errors: [], runs: [run] };
  if (!Object.keys(draft).length) throw new Error("the model's reply held no draft");
  return draft;
}
